### ISSUE TITLE
Error: Target Sequence Length Exceeds Limit (While Using Multiple Species)

### ISSUE THREAD

**Issue by PraveenOraon** [almeidasilvaf/tfhunter#1]
Hello,

 I'm impressed with the tool's capabilities, but I've run into a problem that I believe needs attention.
I encountered the following error while running PlantTFHunter:
`if(hmmer_is_installed()) {
+   tf_counts <- get_tf_counts(proteomes)
+ }
Fatal exception (source file p7_pipeline.c, line 714):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Aborted (core dumped)`
It appears that the target sequence length exceeds the comparison pipeline limit.
Thank you for your assistance.

Best regards,
Praveen

**Comment by almeidasilvaf** [comment]
Hi, @PraveenOraon 

Thank you for your feedback.

Could you briefly describe this object `proteomes` (or print its length, first rows, etc)?

Indeed, it seems like some of the sequences are too long, which is strange. To help debug, you could also show the distribution of sequence lengths for each proteome with:

```r
lapply(proteomes, function(x) summary(Biostrings::width(x)))
```

Best,
Fabricio

**Comment by PraveenOraon** [comment]
Hello,

I appreciate your quick response, @almeidasilvaf. Indeed, the error I encountered was due to the unusually long length of one of the protein sequences I downloaded from the public domain. After removing it, the command ran smoothly, with only a few warnings.

While reading through the documentation for planttfhunter, I came across another valuable tool, Syntenet. I have a question regarding its usage. I am currently working exclusively with members of the Fabaceae family, and I'm interested in identifying family-specific clusters. Do I need to include a large number of families in my analysis, or would it suffice to analyze two candidates per family for some families  to achieve meaningful results? Your guidance on this matter would be greatly appreciated.

Best Regards,
Praveen

**Comment by almeidasilvaf** [comment]
Hi, @PraveenOraon 

Glad to know your problem was solved. 

As for the second question (unrelated to this package), I'd recommend including as many species as you can from other families, otherwise you can't say for sure that they are "family-specific". If you don't have computational power to analyze too many species, what you could do is select representative species for particular taxa within each family (e.g., within the Rosaceae family, pick representatives of each subfamily or genus).

Since your problem with __planttfhunter__ was solved, I will close this issue. Thank you for using __planttfhunter__. ;-)

Best,
Fabricio
